#!/bin/sh

### BEGIN INIT INFO
# Provides:          watchman_worker
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ping file changes to an API of your choice
# Description:       Ping file changes to an API of your choice
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
# DIR=/usr/local/bin/watchman worker
DAEMON_NAME=watchman_worker

# Add any command line options for your daemon here
DAEMON_OPTS=""

# This next line determines what user the script runs as.
DAEMON_USER=$(whoami)

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/watchman/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas /usr/local/bin/watchman worker
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

esac
exit 0
